---
- name: Download VictoriaMetrics
  get_url:
    url: "https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ vm_version }}/victoria-metrics-linux-amd64-v{{ vm_version }}.tar.gz"
    dest: "/tmp/vm.tar.gz"
    mode: "0644"
  notify: restart vm
