---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Test nginx configuration
  ansible.builtin.command:
    cmd: nginx -t
  changed_when: false

- name: Reload nginx
  ansible.builtin.systemd:
    name: "{{ nginx_service_name }}"
    state: reloaded

- name: Restart employee-api
  ansible.builtin.systemd:
    name: employee-api
    state: restarted
    daemon_reload: true

- name: Restart salary-api
  ansible.builtin.systemd:
    name: salary-api
    state: restarted
    daemon_reload: true

- name: Restart attendance-api
  ansible.builtin.systemd:
    name: attendance-api
    state: restarted
    daemon_reload: true
